### PR TITLE
[JSX] Fix Batch Preparation Site Inheritance

### PR DESCRIPTION
**Pull request by HenriRabalais**
blocked by #248

### CODE REVIEW

**Comment by HenriRabalais** [comment]
@ridz1208 this should be ready to merge after #248

**Comment by ridz1208** [comment]
@HenriRabalais there is a conflict now should we close it because of https://github.com/aces/biobank/pull/252

**Comment by ridz1208** [comment]
@HenriRabalais this can technically be closed no ?

**Comment by HenriRabalais** [comment]
Closing because this code has already been implemented

**Pull request closed without merging**
